### ISSUE TITLE
Have you run this script again recently?

### ISSUE THREAD

**Issue by nickloman** [timoast/biorxivData#2]
I'd be keen to see the latest stats, but don't want to hammer the biorxiv server unnecessarily!

**Comment by timoast** [comment]
I haven't, but I'll run it now for you and close this issue when it's finished

**Comment by timoast** [comment]
Update: I ran into some weird bugs in the script and have been busy with other things, but I'll take another crack at it soon and see if I can get it working again

**Comment by timoast** [comment]
Hey @nickloman, new data is up and I did a short analysis here: http://timoast.github.io/2017/10/04/biorxiv-2017-update/
